### ISSUE TITLE
Need urgent help

### ISSUE THREAD

**Issue by adhoc-research** [salmangadit/scope#1]
Hi, I really need some source from this app. It is exactly what I need for my own application. If Salman Gadit or someone can reach out to me I will _really_ appreciate it. I need to know a few basic things which I can't easily piece together from google because I am a complete noob. 

1st question- Is your final app the `prototype` directory in `--username aravindhshankar@gmail.com?` If so, then how do I import it in android studio(many errors popped up)?

2nd question- Can your app detect edges and automatically OCR after detection? If not how can I do that?

3rd question- Your app was for business cards, which have unpredictable formats, while mine is for 8 types of fixed formats. How do I train tesseract to identify those formats and fill the correct fields?

4th question- I read your project papers, and it appears you have used OpenCV. I am using Leptonica. Which one is more accurate(your papers did not mention Leptonica)?

5th question- How do I display editable fields after the OCR? After scanning, the app will display a form of sorts, which will contain the fields(e.g: name, age, etc.) the OCR had filled, so that if the OCR has made a mistake it can be manually corrected.

I know it is a lot to ask of you, but if you can give me these answers I will be forever grateful. Please, please, please help a noob out :pray: :pray:

**Comment by salmangadit** [comment]
Hi there!

Glad you find this useful, and although it has been a very long time since we did this project, I will help wherever I can :)

To answer each of your questions:
1. Yes, the final app (which was never production ready btw, but worked) is in the directory you specified. When we implemented it, there was no Android Studio! :smile: We built all on Eclipse. You can try doing that if you want, although porting this to Android Studio should not be so hard. I might try to do this sometime, but if you are on a tight deadline, I recommend you do not wait for me to do that.
2. Yes, you can set that up. To understand how this edge detection works, and if it is what you are looking for, I recommend trying out the Skew Test App located [here](https://github.com/salmangadit/scope/blob/490f8a314fb66948f4eacca94797efc810c5792a/%20scope-ocr%20--username%20operationgenesis%40gmail.com/Skew%20Test%20App/hiii/src/com/example/hiii/MainActivity.java). If your use case is the same, you can simply call the OCR module right after the edge detection is done. We just decided to do it one step at a time because it was easier to demonstrate our algorithms seperately easier that way.
3. I think you don't need to train tesseract to do anything. Just make sure you are using it with the CUBE libraries, which are pretrained for identifying text as accurately as possible. Please note, my information could be outdated by a few years as I haven't tried this in a while. If you have 8 pre-defined formats, you can write a custom set of modules for your image processing portion to extract the contents in a custom way for each format. In that way, you will 100% be able to extract the text locations correctly. Then you can use our background segmentation, text segmentation and text clustering algorithms to refine your image as accurately as possible and trust that tesseract will do the rest to the maximum capability.
4. I haven't used Leptonica, but as far as I am aware, Leptonica is a collection of image processing algorithms designed for certain tasks, where as OpenCV is a raw image processing library with basic functions, which you will need to build algorithms on top of. When we did the project, we either were not aware of Leptonica, or it just was not refined/documented enough to be of use. That being said, we also used OpenCV because it runs natively on Android and we needed that for our project to work.
5. This is an easy one - this is exactly what we did in this [Activity](https://github.com/salmangadit/scope/blob/master/%20scope-ocr%20--username%20aravindh.shankar.91%40gmail.com/Prototype/Scope/src/com/example/scope/Contacts.java). You just have to store all the parsed results in EditText widgets :) Should be simple enough!

I think this is everything you requested. Feel free to follow up with any other questions. If I get time, I will try to get it building with the latest OpenCV and on Android Studio, but I cannot promise this, as I may not have time in the next few weeks to do so :)

**Comment by salmangadit** [comment]
I've committed a working Android Studio build here: https://github.com/salmangadit/scope/tree/androidstudio_port

I haven't tested the output, but it should work. Please ensure you have a folder called 'Scope' in your sd card directory and the [tessdata ](https://github.com/tesseract-ocr/tessdata)files are stored in a subfolder called 'tessdata'.

**Comment by adhoc-research** [comment]
@salmangadit Thanks ALOT. You helped me, even though you did this a long time ago and you don't have much time(Honestly, I didn't expect you to respond :smile:). 
I have understood most of your points except for number 4. Do you mean to say that Leptonica is worse than OpenCV(I know you have not tried leptonica)? Or if I have OpenCV I have to custom make algorithms?
I still think tesseract needs to be trained in order to recognise templates though.
And duude, you _actually_ made the android studio version just for me? That's so awesome of you!! I will sing your praises one day :stuck_out_tongue_winking_eye:

**Comment by salmangadit** [comment]
Hey there @machomachopadre, you're welcome, glad to help :) Unfortunately, I am not an expert in Leptonica, so this will have to be your judgement call and you will have to figure it out. We have written the algorithms for most of the parts from scratch to fit our custom needs.

You're welcome :) I forgot to mention, the android studio port is in the release/Scope folder.

Cheers!

**Comment by adhoc-research** [comment]
@salmangadit I have pretty much figured out your project, except for 2 things. 
1) What does StringParser.java do? 
2) How do I use the skew test app, if I already have the bitmap?
If you could help me out here, that would be awesome. Also, this is my last question :)

**Comment by salmangadit** [comment]
For both parts, I am tagging @varunganesh91 who implemented them in our team. 

From my input on them, the StringParser parses the OCR-ed text and figures out which parts are the Name, Email, Phone number etc so it can be set on the contacts field.

If you've figured out everything else, the Skew test app should be very simple :smile: ! I believe the Skew test app has a button, where it will open your Gallery. Select your image and it will apply the EdgeDetection algorithms on it, with log statements in logcat. Varun, tagged above should be able to correct you if my input is wrong :8ball:

**Comment by varunganesh117** [comment]
@machomachopadre Good to hear from you and glad that you are benefitting from our project

Thanks @salmangadit, you're right about both questions. Let me just add on to them.

Regarding your first question, after having edge-detected, cropped, cleaned and OCR'ed the image, we had the final task of reading contact information out of the text, the StringParser was written to address that (unintended pun).

The OCR'd text is passed to the StringParser's method and from there it's all about string manipulation and assigning a certain confidence score to each of the lines by comparing them to (very minimal) dictionaries maintained for keywords related to street addresses, pincodes, e-mails, phone numbers etc.

This was done towards the end of the project and wasn't our most important task to focus on, so I'd advise you not to expect it to work out-of-the-box for most situations.

I am not sure of your exact needs in your project, but if you do require such address parsing, i'd recommend looking at <a href="https://developers.google.com/maps/documentation/geocoding/intro">Google's Geocoding API</a> which offers simpler ways to get this information. This is assuming your app can access the internet, the USP for our app was that it would work without a 3G or WiFi connection. If not, I would recommend looking at some basic machine learning patterns to parse contact information and training the algorithm with large sets of related data.

**Comment by varunganesh117** [comment]
Also, regarding your second question, I believe you can use SkewTestApp by just importing it and running it on an android phone. The app lets you select an image from your gallery (preferably images of rectangular cards placed on surfaces), detects the edges, rotates it, if skewed, to a horizontal position and crops out the card.

Finally, the app displays the original image and the cropped card image one below the other.

(This is what I remember and can see from scanning through the code, I hope it works as I've described)

**Comment by salmangadit** [comment]
Closing this since there has been no noise in 6 days :)

**Comment by adhoc-research** [comment]
Hello again @salmangadit and @varunganesh91. Thank you for your help! Even though I didn't actually use this project(I switched my idea) for my final submission, I became interested. Sorry this is late(bit busy with college work) but I want to complete this app. To start off I would like to ask what do all the "obj" classes do(ex: AddressObj)? Also, I believe a lot of code Contacts.java is based around the add contact button. If I were to only need the field filling function, what code should I cut out? Thanks!!

**Comment by salmangadit** [comment]
Hey, no worries! I think it would take too long to explain what all the classes do. I would recommend starting from ScanFragment and working your way through the code. It is pretty sequential and we weren't woried about code cleanliness back then but that means it should be fairly simple to navigate :) Let me know if you have any specific questions
